# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from official Python image with minimal footprint
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Ensure pipes and output are unbuffered
ENV PYTHONUNBUFFERED=1

# Install required system dependencies
# tzdata for proper timezone handling if needed
RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY server.py ./
COPY smithery.yaml ./
COPY README.md ./

# Expose no ports since we use stdio transport

# Default command to run the MCP server
CMD ["python", "server.py"]
